### ISSUE TITLE
Incomplete AST

### ISSUE THREAD

**Issue by NeomMob** [xoofx/markdig#433]
I am trying to analyze a parsed document using `Document?.Descendants()` but some blocks like `MathBlock` even if they are parsed and rendered properly are not found in the AST.
I did a similar test with `FencedCodeBlock` and it works as expected.
What is the reason do not have them in the AST?

**Comment by xoofx** [comment]
> What is the reason do not have them in the AST?

Can you show a small repro with the exact setup of the pipeline you are using?
