### ISSUE TITLE
StackOverflowException is throw when converting special markdown to HTML

### ISSUE THREAD

**Issue by leonyang12** [xoofx/markdig#497]
We use Markdig in our code to convert Markdown to HTML. It works perfect in most cases w.r.t. to performance. Recently we received reports that the library hangs and throws StackOverflowException when processing some special markdowns.

Here are the sample code:
`string input = <special markdown input>;
var pipeline = new MarkdownPipelineBuilder().UseAdvancedExtensions().Build();

string result = Markdown.ToHtml(input, pipeline);`

@xoofx, I wouldn't paste the markdown payload here due to security reason, please let me know the best option to share it out to continue investigation.

**Comment by xoofx** [comment]
Could you compile a local version of Markdig, debug it with your markdown and try to extract a smaller repro that you could post?

**Comment by MihaZupan** [comment]
Feel free to share the input via any contact on my profile.

**Comment by leonyang12** [comment]
@xoofx , thanks for the quick response. I reached out to @MihaZupan and shared the markdown input with repro.

**Comment by leonyang12** [comment]
@MihaZupan , has there been any update with investigation?

**Comment by leonyang12** [comment]
@xoofx , will you be able to review @MihaZupan 's fix? Thanks

**Comment by leonyang12** [comment]
@xoofx, when can we expect a new version with the fix?
