### ISSUE TITLE
Allow youtube-nocookie.com for embedded youtube videos

### ISSUE THREAD

**Issue by peterdongan** [xoofx/markdig#503]
This is a great project. 

I was wondering if you might add support for youtube-nocookie.com for embedded videos? 

Embedded YouTube videos set a number of tracking cookies when the page is opened when the default URI. However if you use youtube-nocookie then it doesn't set these tracking cookies. This is to facilitate compliance with GDPR regulations in the EU.

**Comment by xoofx** [comment]
This is what I get when accessing github-nocookie.com on https, doesn't look like mainstream:

![image](https://user-images.githubusercontent.com/715038/104853355-90d9d880-5900-11eb-8e6a-7fde1beb5f45.png)

You can do that on your own in your project by implementing a [`IHostProvider`](https://github.com/xoofx/markdig/blob/master/src/Markdig/Extensions/MediaLinks/IHostProvider.cs) with the medialink extension, so there is no need to add a specific handling for this provider.

**Comment by peterdongan** [comment]
Thanks. I'll do that.

Yeah I was confused by that too. It's official though - just only provided for the purpose I suggested here. You can access it on youtube by selecting Share -> Embed and selecting Enable enhanced privacy. 

![image](https://user-images.githubusercontent.com/32374349/104853522-53be1800-58f9-11eb-87f6-9c2b82a13cc2.png)
