### ISSUE TITLE
disable leading and ending paragraph

### ISSUE THREAD

**Issue by schmitch** [xoofx/markdig#506]
Hello currently when I'm rendering a simple html string to markdown via markdig:

```
Console.WriteLine(Markdig.ToHtml("test **hello**"));
```

and the output will be `<p>test <strong>hello</strong></p>` is there a way to stop rendering the p tag?

**Comment by xoofx** [comment]
No, it's part of CommonMark. You can workaround by trimming start/end of the string.

**Comment by jjxtra** [comment]
Trimming is tricky especially if text has newlines, you can end up trimming out paragraph tags inadvertently.

**Comment by xoofx** [comment]
> Trimming is tricky especially if text has newlines, you can end up trimming out paragraph tags inadvertently.

Trimming is not tricky, because trimming only happens on the edges, so it won't trim intermediate paragraphs

**Comment by jjxtra** [comment]
Trimming <p> and </p> can screw up the html. This bit me when I trimmed generated text of <p>paragraph 1 text</p>...<p>paragraph 2 text</p>

**Comment by xoofx** [comment]
> Trimming leading/tailing <p> and </p> can screw up the html. This bit me when I trimmed generated text of <p>paragraph 1 text</p>...<p>paragraph 2 text</p>

Right, and if it is more complicated than that, you should use something like [AngleSharp](https://github.com/AngleSharp/AngleSharp).

Implementing it in Markdig would not be not more simple.
