### ISSUE TITLE
[version 0.23.0] [Blazor] Failed to find a valid digest in the 'integrity' attribute for resource...

### ISSUE THREAD

**Issue by tesar-tech** [xoofx/markdig#507]
Hi,
I just had an issue with error message:

>Failed to find a valid digest in the 'integrity' attribute for resource 'https://localhost:5001/_framework/Markdig.dll' with computed SHA-256 integrity 'KCZKiUNlOdADFOyj5m2qCydqygJKiiplgvBjhjseWw8='. The resource has been blocked.

Not sure what was actually wrong, but I "fixed" that by downgrading to version 0.22.1. (So I think it's related to markdig).

Using Blazor WA on client side.

**Comment by xoofx** [comment]
Can't tell, but I would say that it's a Blazor bug rather than a bug in Markdig. For example [here](https://github.com/dotnet/aspnetcore/issues/28692)

Closing as probably invalid.
