### ISSUE TITLE
Parser: Inline HTML combined with code block (if no blank  line)

### ISSUE THREAD

**Issue by paultechguy** [xoofx/markdig#509]
When using the parser, if a code block immediately follows inline HTML, they are both combined into a single HTML block.  See end for info on the CommonMark spec.  The CommonMark online editor handles both cases below fine, parsing things as two separate blocks.  Markdig for example, if markdown is:

```html
    <img src="http://domain.com" />
    ```html
      <strong>Foo</strong>
    ```
```
The above is returned by the parser's *Parse* method as one whole *HtmlBlock*.  The way to fix this is to separate the inline HTML by blank line(s):


```html
    <img src="http://domain.com" />
    
    ```html
      <strong>Foo</strong>
    ```
```
The above is returned as two separate blocks by the Markdig parser.

**Is there a way for the Markdig parser to return two separate blocks regardless of format?**

The [CommonMark spec](https://spec.commonmark.org/0.29/#fenced-code-blocks) indicates:
*A fenced code block may interrupt a paragraph, and does not require a blank line either before or after.*

**Comment by xoofx** [comment]
> Is there a way for the Markdig parser to return two separate blocks regardless of format?
> The CommonMark spec indicates:
> A fenced code block may interrupt a paragraph, and does not require a blank line either before or after.

Nope, but it's indeed a corner case. I believe most implementers took the HTML rule as superseding the fenced block rule.

Almost CommonMark implementations are following the [same behavior](https://babelmark.github.io/?text=%3Cimg+src%3D%22http%3A%2F%2Fdomain.com%22+%2F%3E%0A%60%60%60html%0A++++++%3Cstrong%3EFoo%3C%2Fstrong%3E%0A%60%60%60) than markdig. Seems that GitHub flavored choose a different path on that particular case, which is unfortunate...

So we can't really change that, unless you are willing to make a PR with an extension to add an option to turn that off, but I'm not sure how easy it is to fit that in...
