### ISSUE TITLE
strange output for simple string

### ISSUE THREAD

**Issue by schmitch** [xoofx/markdig#513]
hello, currently we have the following markdown string: `**C:\\**test\\`

we would expect an output of `<p><strong>C:\</strong>test\` unfortunatly we get the following `<p>**C:\**test\</p>` , is there a reason why that is the case?

**Comment by xoofx** [comment]
Yes, you can see that all CommonMark implementations behave the same [here](https://babelmark.github.io/?text=**C%3A%5C%5C**test%5C%5C)

That's expected as per [CommonMark specs for emphasis](https://spec.commonmark.org/0.29/#emphasis-and-strong-emphasis)

> A right-flanking delimiter run is a delimiter run that is (1) not preceded by Unicode whitespace, and either (2a) not preceded by a punctuation character, or (2b) preceded by a punctuation character and followed by Unicode whitespace or a punctuation character. For purposes of this definition, the beginning and the end of the line count as Unicode whitespace.

The case here in is that on the right of `**C:\\**` there is `test` which is not a whitespace or a punctuation.

**Comment by schmitch** [comment]
so is there a way to additional escape the string to satisfy the requirement without adding whitespace?

**Comment by xoofx** [comment]
> so is there a way to additional escape the string to satisfy the requirement without adding whitespace?

Nope, as per the spec, punctuation or whitespace.

You would have to change it like that `**C:\\**test\\`  or write directly HTML inlines `<strong>C:\\</strong>test\\`

**Comment by schmitch** [comment]
thanks, I think that helped me!
