### ISSUE TITLE
How to not encode query string parameters in link url

### ISSUE THREAD

**Issue by JoshClose** [xoofx/markdig#514]
When a query string is in a URL, it is getting encoded. Is there a way to have it not encoded?

```cs
Markdown.ToHtml("[text](/foo/bar?a=b&c=d#fragment)")
```
outputs
```html
<p><a href="/foo/bar?a=b&amp;c=d#fragment">text</a></p>
```
I would like
```html
<p><a href="/foo/bar?a=b&c=d#fragment">text</a></p>
```

**Comment by MihaZupan** [comment]
You should be able to use the `LinkRewriter` on `HtmlRenderer` to remove the query part

**Comment by JoshClose** [comment]
I don't want the query removed. I just want to keep it intact.

**Comment by xoofx** [comment]
> When a query string is in a URL, it is getting encoded. Is there a way to have it not encoded?

Nope. It requires a change to the code to add an option to HtmlRenderer to avoid the Url encoding. The CommonMark specs don't enforce the encoding, so I would believe that it would be ok to have an option. PR welcome.

**Comment by MihaZupan** [comment]
Ah, sorry. One way would be to use a custom `LinkInlineRenderer` and not call `WriteEscapeUrl`.

Why would you want to do this though?

**Comment by JoshClose** [comment]
> Why would you want to do this though?

So when someone clicks the link, it goes to the correct address. I feel like I'm missing something or am confused about this.

**Comment by xoofx** [comment]
> So when someone clicks the link, it goes to the correct address. I feel like I'm missing something or am confused about this.

That's weird because the encoding has been here for years without being an issue... there is something else...

**Comment by xoofx** [comment]
To be fair, I don't recall why markdig escape `&` to `&amp;` in an URL...hm....

**Comment by xoofx** [comment]
it could be a bug actually, I really don't get this `&` to `&amp;`, it's HTML escape, not URL....

**Comment by xoofx** [comment]
babelmark is showing the same behavior for [almost all Markdown implems](https://babelmark.github.io/?text=%5Btext%5D(%2Ffoo%2Fbar%3Fa%3Db%26c%3Dd%23fragment))... ok, now I'm confused! 😅

**Comment by xoofx** [comment]
while the [example 591](https://spec.commonmark.org/0.29/#example-591) in the specs seems to escape to `&` to `&amp;`... so yeah, it seems the correct behavior, not sure what to thing about it, will have to think about it with a clearer mind tomorrow!

**Comment by xoofx** [comment]
> So when someone clicks the link, it goes to the correct address. I feel like I'm missing something or am confused about this.

By curiosity, with which browser are you actually testing this link?

**Comment by JoshClose** [comment]
Looks like it works as Chrome/Edge will change the raw url with `&amp;` to just `&`. Maybe this is a non-issue. It seemed like it shouldn't and the online markdown one I tested with showed it didn't, so here I am. :) https://dillinger.io/ Though now seeing that browsers will correct the html in the link, maybe this one is outputting the same as MarkDig.

**Comment by JoshClose** [comment]
If CommonMark shows it should be encoded then this is a non-issue. I don't understand why it would encode parts of the actual URL for an href, but I guess that's how it is.

**Comment by JoshClose** [comment]
Thanks for looking into this.

**Comment by jjxtra** [comment]
What would it take to add an optional bool property somewhere to the pipeline to not write escaped urls?
