### ISSUE TITLE
How to setup a pipeline to ignore certain markdown? #Question

### ISSUE THREAD

**Issue by fscopel** [xoofx/markdig#523]
I need to NOT render for example `[Google](http://google.com)` into this `<p><a href="http://google.com">Google</a></p>`
Instead I want to result to be `<p>[Google](http://google.com)</p>`

How do I go about setting up the pipeline this way?

**Comment by xoofx** [comment]
You can try to to create an extension that would remove the `LinkInlineParser` predefined in [MarkdownPipelineBuilder](https://github.com/xoofx/markdig/blob/640196a18f49ef1d87af044fe6ce70de21d47e8a/src/Markdig/MarkdownPipelineBuilder.cs#L43)

**Comment by MihaZupan** [comment]
You can access the parsers on the builder, so you should be able to simplify that to
```c#
var builder = new MarkdownPipelineBuilder();
builder.InlineParsers.TryRemove<LinkInlineParser>();
MarkdownPipeline pipeline = builder.Build();
```

**Comment by fscopel** [comment]
I was just about to post! I was playing around with it a bit more, and indeed the Extensions don't seem nescessary.

```
        static void Main(string[] args)
        {
            var sampleMarkdown = @"[Google](http://google.com)";

            var modelPipeline = new MarkdownPipelineBuilder();

            var parser = modelPipeline.InlineParsers.First(o => o is LinkInlineParser);
            modelPipeline.InlineParsers.Remove(parser);

            var pipeline = modelPipeline.Build();

            var renderedHtml = Markdown.ToHtml(sampleMarkdown, pipeline);

            Console.WriteLine(renderedHtml);
            Console.ReadLine();
        }
```
