### ISSUE TITLE
Trying to get the pipe table to work

### ISSUE THREAD

**Issue by Dennizzzzz** [xoofx/markdig#533]
Maybe a N00b question, but I'm trying to get a pipe table to work.
And I cannot find any C# example code.

Tried this:

```
var h = "a|b|b";
h += "--|--|--";
h += "1|2|3";
var r = MarkDig.Markdown.ToHtml();
```

but r results in:
`<p>a|b|c--|--|--1|2|3</p>`

documentation : [here](https://github.com/xoofx/markdig/blob/master/src/Markdig.Tests/Specs/PipeTableSpecs.md) is not really helping...

Update:
Tried this, but also not working:
```
   var p = new Markdig.MarkdownPipelineBuilder().UsePipeTables().Build();
   var h = "a|b|c";
   h += "--|--|--";
   h += "1|2|3";
   var r = Markdig.Markdown.ToHtml(h,p);
```

What am I missing?

**Comment by MihaZupan** [comment]
You'll need to add some new lines there - you're currently trying to render `a|b|b--|--|--1|2|3`

**Comment by Dennizzzzz** [comment]
Thanks to MihaZupan...

```
   var p = new Markdig.MarkdownPipelineBuilder().UsePipeTables().Build();
   var h = "a|b|c" + Environment.NewLine;
   h += "--|--|--" + Environment.NewLine;
   h += "1|2|3" + Environment.NewLine;
   var r = Markdig.Markdown.ToHtml(h,p);
```

returns:

```
<table>
<thead>
<tr>
<th>a</th>
<th>b</th>
<th>c</th>
</tr>
</thead>
<tbody>
<tr>
<td>1</td>
<td>2</td>
<td>3</td>
</tr>
</tbody>
</table>
```
