### ISSUE TITLE
0.24 Release build issue

### ISSUE THREAD

**Issue by stevehatch** [xoofx/markdig#536]
After upgrading from 0.23 to 0.24 our app runs fine in debug but crashes in release.  Our QA department tells me it's only in iOS if that helps

Here is the AppCenter caught exception:

{
  "length": 0,
  "offset": 0,
  "id": "57592d9c-4ced-4b2c-8dc6-481e04533d0b",
  "exception": {
    "type": "System.TypeInitializationException",
    "message": "The type initializer for 'Markdig.Markdown' threw an exception.",
    "stackTrace": "  at MarkdownView.MarkdownView.RenderMarkdown () <0x104a4ad78 + 0x000e0> in <5cf03c4fb6f1467395ccd8cb7e4984eb#c958e5ce99374bbbd9922e9f71fe65a3>:0 \n  at MarkdownView.MarkdownView.OnMarkdownChanged (Xamarin.Forms.BindableObject bindable, System.Object oldValue, System.Object newValue) <0x104a4ad00 + 0x0005b> in <5cf03c4fb6f1467395ccd8cb7e4984eb#c958e5ce99374bbbd9922e9f71fe65a3>:0 \n  at Xamarin.Forms.BindableObject.SetValueActual (Xamarin.Forms.BindableProperty property, Xamarin.Forms.BindableObject+BindablePropertyContext context, System.Object value, System.Boolean currentlyApplying, Xamarin.Forms.Internals.SetValueFlags attributes, System.Boolean silent) <0x1057f44b8 + 0x001e7> in <978ec34c5c9c4c4eb3d73b6da958bcd6#c958e5ce99374bbbd9922e9f71fe65a3>:0 \n  at Xamarin.Forms.BindableObject.SetValueCore (Xamarin.Forms.BindableProperty property, System.Object value, Xamarin.Forms.Internals.SetValueFlags attributes, Xamarin.Forms.BindableObject+SetValuePrivateFlags privateAttributes) <0x1057f4074 + 0x0020f> in <978ec34c5c9c4c4eb3d73b6da958bcd6#c958e5ce99374bbbd9922e9f71fe65a3>:0 \n  at Xamarin.Forms.BindingExpression.ApplyCore (System.Object sourceObject, Xamarin.Forms.BindableObject target, Xamarin.Forms.BindableProperty property, System.Boolean fromTarget) <0x1057fc948 + 0x0046b> in <978ec34c5c9c4c4eb3d73b6da958bcd6#c958e5ce99374bbbd9922e9f71fe65a3>:0 \n  at Xamarin.Forms.BindingExpression.Apply (System.Object sourceObject, Xamarin.Forms.BindableObject target, Xamarin.Forms.BindableProperty property) <0x1057fc6cc + 0x0011b> in <978ec34c5c9c4c4eb3d73b6da958bcd6#c958e5ce99374bbbd9922e9f71fe65a3>:0 \n  at Xamarin.Forms.Binding.Apply (System.Object context, Xamarin.Forms.BindableObject bindObj, Xamarin.Forms.BindableProperty targetProperty, System.Boolean fromBindingContextChanged) <0x1057f9ec4 + 0x0010f> in <978ec34c5c9c4c4eb3d73b6da958bcd6#c958e5ce99374bbbd9922e9f71fe65a3>:0 \n  at Xamarin.Forms.BindableObject.ApplyBindings (System.Boolean skipBindingContext, System.Boolean fromBindingContextChanged) <0x1057f470c + 0x000d7> in <978ec34c5c9c4c4eb3d73b6da958bcd6#c958e5ce99374bbbd9922e9f71fe65a3>:0 \n  at Xamarin.Forms.BindableObject.SetInheritedBindingContext (Xamarin.Forms.BindableObject bindable, System.Object value) <0x1057f3380 + 0x000df> in <978ec34c5c9c4c4eb3d73b6da958bcd6#c958e5ce99374bbbd9922e9f71fe65a3>:0 \n  at Xamarin.Forms.Element.SetChildInheritedBindingContext (Xamarin.Forms.Element child, System.Object context) <0x10582d4c4 + 0x00013> in <978ec34c5c9c4c4eb3d73b6da958bcd6#c958e5ce99374bbbd9922e9f71fe65a3>:0 \n  at Xamarin.Forms.Element.<OnBindingContextChanged>b__83_0 (Xamarin.Forms.BindableObject child, System.Object bc) <0x10582f1b0 + 0x0006f> in <978ec34c5c9c4c4eb3d73b6da958bcd6#c958e5ce99374bbbd9922e9f71fe65a3>:0 \n  at Xamarin.Forms.BindableObjectExtensions.PropagateBindingContext[T] (Xamarin.Forms.BindableObject self, System.Collections.Generic.IList`1[T] children, System.Action`2[T1,T2] setChildBindingContext) <0x1057f5620 + 0x000fb> in <978ec34c5c9c4c4eb3d73b6da958bcd6#c958e5ce99374bbbd9922e9f71fe65a3>:0 \n  at Xamarin.Forms.Element.OnBindingContextChanged () <0x10582c410 + 0x000d3> in <978ec34c5c9c4c4eb3d73b6da958bcd6#c958e5ce99374bbbd9922e9f71fe65a3>:0 \n  at Xamarin.Forms.View.OnBindingContextChanged () <0x1059065d4 + 0x00053> in <978ec34c5c9c4c4eb3d73b6da958bcd6#c958e5ce99374bbbd9922e9f71fe65a3>:0 \n  at Xamarin.Forms.Grid.OnBindingContextChanged () <0x105844f94 + 0x0001b> in <978ec34c5c9c4c4eb3d73b6da958bcd6#c958e5ce99374bbbd9922e9f71fe65a3>:0 \n  at Xamarin.Forms.BindableObject.BindingContextPropertyChanged (Xamarin.Forms.BindableObject bindable, System.Object oldvalue, System.Object newvalue) <0x1057f4940 + 0x00047> in <978ec34c5c9c4c4eb3d73b6da958bcd6#c958e5ce99374bbbd9922e9f71fe65a3>:0 \n  at Xamarin.Forms.BindableObject.SetValueActual (Xamarin.Forms.BindableProperty property, Xamarin.Forms.BindableObject+BindablePropertyContext context, System.Object value, System.Boolean currentlyApplying, Xamarin.Forms.Internals.SetValueFlags attributes, System.Boolean silent) <0x1057f44b8 + 0x001e7> in <978ec34c5c9c4c4eb3d73b6da958bcd6#c958e5ce99374bbbd9922e9f71fe65a3>:0 \n  at Xamarin.Forms.BindableObject.SetValueCore (Xamarin.Forms.BindableProperty property, System.Object value, Xamarin.Forms.Internals.SetValueFlags attributes, Xamarin.Forms.BindableObject+SetValuePrivateFlags privateAttributes) <0x1057f4074 + 0x0020f> in <978ec34c5c9c4c4eb3d73b6da958bcd6#c958e5ce99374bbbd9922e9f71fe65a3>:0 \n  at Xamarin.Forms.BindableObject.SetValue (Xamarin.Forms.BindableProperty property, System.Object value, System.Boolean fromStyle, System.Boolean checkAccess) <0x1057f3d94 + 0x0008b> in <978ec34c5c9c4c4eb3d73b6da958bcd6#c958e5ce99374bbbd9922e9f71fe65a3>:0 \n  at Xamarin.Forms.BindableObject.set_BindingContext (System.Object value) <0x1057f2170 + 0x00047> in <978ec34c5c9c4c4eb3d73b6da958bcd6#c958e5ce99374bbbd9922e9f71fe65a3>:0 \n  at InspectFlow.Core.Controls.LineItemControl.set_Items (System.Collections.ObjectModel.ObservableCollection`1[T] value) <0x104aa92b4 + 0x000ff> in <5cf03c4fb6f1467395ccd8cb7e4984eb#c958e5ce99374bbbd9922e9f71fe65a3>:0 \n  at InspectFlow.Core.Controls.LineItemControl.ItemsChanged (Xamarin.Forms.BindableObject bindable, System.Object oldValue, System.Object newValue) <0x104aa9aa8 + 0x00083> in <5cf03c4fb6f1467395ccd8cb7e4984eb#c958e5ce99374bbbd9922e9f71fe65a3>:0 \n  at Xamarin.Forms.BindableObject.SetValueActual (Xamarin.Forms.BindableProperty property, Xamarin.Forms.BindableObject+BindablePropertyContext context, System.Object value, System.Boolean currentlyApplying, Xamarin.Forms.Internals.SetValueFlags attributes, System.Boolean silent) <0x1057f44b8 + 0x001e7> in <978ec34c5c9c4c4eb3d73b6da958bcd6#c958e5ce99374bbbd9922e9f71fe65a3>:0 \n  at Xamarin.Forms.BindableObject.SetValueCore (Xamarin.Forms.BindableProperty property, System.Object value, Xamarin.Forms.Internals.SetValueFlags attributes, Xamarin.Forms.BindableObject+SetValuePrivateFlags privateAttributes) <0x1057f4074 + 0x0020f> in <978ec34c5c9c4c4eb3d73b6da958bcd6#c958e5ce99374bbbd9922e9f71fe65a3>:0 \n  at Xamarin.Forms.BindingExpression.ApplyCore (System.Object sourceObject, Xamarin.Forms.BindableObject target, Xamarin.Forms.BindableProperty property, System.Boolean fromTarget) <0x1057fc948 + 0x0046b> in <978ec34c5c9c4c4eb3d73b6da958bcd6#c958e5ce99374bbbd9922e9f71fe65a3>:0 \n  at Xamarin.Forms.BindingExpression.Apply (System.Object sourceObject, Xamarin.Forms.BindableObject target, Xamarin.Forms.BindableProperty property) <0x1057fc6cc + 0x0011b> in <978ec34c5c9c4c4eb3d73b6da958bcd6#c958e5ce99374bbbd9922e9f71fe65a3>:0 \n  at Xamarin.Forms.Binding.Apply (System.Object context, Xamarin.Forms.BindableObject bindObj, Xamarin.Forms.BindableProperty targetProperty, System.Boolean fromBindingContextChanged) <0x1057f9ec4 + 0x0010f> in <978ec34c5c9c4c4eb3d73b6da958bcd6#c958e5ce99374bbbd9922e9f71fe65a3>:0 \n  at Xamarin.Forms.BindableObject.ApplyBindings (System.Boolean skipBindingContext, System.Boolean fromBindingContextChanged) <0x1057f470c + 0x000d7> in <978ec34c5c9c4c4eb3d73b6da958bcd6#c958e5ce99374bbbd9922e9f71fe65a3>:0 \n  at Xamarin.Forms.BindableObject.SetInheritedBindingContext (Xamarin.Forms.BindableObject bindable, System.Object value) <0x1057f3380 + 0x000df> in <978ec34c5c9c4c4eb3d73b6da958bcd6#c958e5ce99374bbbd9922e9f71fe65a3>:0 \n  at Xamarin.Forms.Element.SetChildInheritedBindingContext (Xamarin.Forms.Element child, System.Object context) <0x10582d4c4 + 0x00013> in <978ec34c5c9c4c4eb3d73b6da958bcd6#c958e5ce99374bbbd9922e9f71fe65a3>:0 \n  at Xamarin.Forms.Element.<OnBindingContextChanged>b__83_0 (Xamarin.Forms.BindableObject child, System.Object bc) <0x10582f1b0 + 0x0006f> in <978ec34c5c9c4c4eb3d73b6da958bcd6#c958e5ce99374bbbd9922e9f71fe65a3>:0 \n  at Xamarin.Forms.BindableObjectExtensions.PropagateBindingContext[T] (Xamarin.Forms.BindableObject self, System.Collections.Generic.IList`1[T] children, System.Action`2[T1,T2] setChildBindingContext) <0x1057f5620 + 0x000fb> in <978ec34c5c9c4c4eb3d73b6da958bcd6#c958e5ce99374bbbd9922e9f71fe65a3>:0 \n  at Xamarin.Forms.Element.OnBindingContextChanged () <0x10582c410 + 0x000d3> in <978ec34c5c9c4c4eb3d73b6da958bcd6#c958e5ce99374bbbd9922e9f71fe65a3>:0 \n  at Xamarin.Forms.View.OnBindingContextChanged () <0x1059065d4 + 0x00053> in <978ec34c5c9c4c4eb3d73b6da958bcd6#c958e5ce99374bbbd9922e9f71fe65a3>:0 \n  at Xamarin.Forms.BindableObject.SetInheritedBindingContext (Xamarin.Forms.BindableObject bindable, System.Object value) <0x1057f3380 + 0x000ef> in <978ec34c5c9c4c4eb3d73b6da958bcd6#c958e5ce99374bbbd9922e9f71fe65a3>:0 \n  at Xamarin.Forms.Element.SetChildInheritedBindingContext (Xamarin.Forms.Element child, System.Object context) <0x10582d4c4 + 0x00013> in <978ec34c5c9c4c4eb3d73b6da958bcd6#c958e5ce99374bbbd9922e9f71fe65a3>:0 \n  at Xamarin.Forms.Element.<OnBindingContextChanged>b__83_0 (Xamarin.Forms.BindableObject child, System.Object bc) <0x10582f1b0 + 0x0006f> in <978ec34c5c9c4c4eb3d73b6da958bcd6#c958e5ce99374bbbd9922e9f71fe65a3>:0 \n  at Xamarin.Forms.BindableObjectExtensions.PropagateBindingContext[T] (Xamarin.Forms.BindableObject self, System.Collections.Generic.IList`1[T] children, System.Action`2[T1,T2] setChildBindingContext) <0x1057f5620 + 0x000fb> in <978ec34c5c9c4c4eb3d73b6da958bcd6#c958e5ce99374bbbd9922e9f71fe65a3>:0 \n  at Xamarin.Forms.Element.OnBindingContextChanged () <0x10582c410 + 0x000d3> in <978ec34c5c9c4c4eb3d73b6da958bcd6#c958e5ce99374bbbd9922e9f71fe65a3>:0 \n  at Xamarin.Forms.View.OnBindingContextChanged () <0x1059065d4 + 0x00053> in <978ec34c5c9c4c4eb3d73b6da958bcd6#c958e5ce99374bbbd9922e9f71fe65a3>:0 \n  at Xamarin.Forms.Grid.OnBindingContextChanged () <0x105844f94 + 0x0001b> in <978ec34c5c9c4c4eb3d73b6da958bcd6#c958e5ce99374bbbd9922e9f71fe65a3>:0 \n  at Xamarin.Forms.BindableObject.SetInheritedBindingContext (Xamarin.Forms.BindableObject bindable, System.Object value) <0x1057f3380 + 0x000ef> in <978ec34c5c9c4c4eb3d73b6da958bcd6#c958e5ce99374bbbd9922e9f71fe65a3>:0 \n  at Xamarin.Forms.TemplatedView.SetChildInheritedBindingContext (Xamarin.Forms.Element child, System.Object context) <0x1058fda94 + 0x00027> in <978ec34c5c9c4c4eb3d73b6da958bcd6#c958e5ce99374bbbd9922e9f71fe65a3>:0 \n  at Xamarin.Forms.Element.<OnBindingContextChanged>b__83_0 (Xamarin.Forms.BindableObject child, System.Object bc) <0x10582f1b0 + 0x0006f> in <978ec34c5c9c4c4eb3d73b6da958bcd6#c958e5ce99374bbbd9922e9f71fe65a3>:0 \n  at Xamarin.Forms.BindableObjectExtensions.PropagateBindingContext[T] (Xamarin.Forms.BindableObject self, System.Collections.Generic.IList`1[T] children, System.Action`2[T1,T2] setChildBindingContext) <0x1057f5620 + 0x000fb> in <978ec34c5c9c4c4eb3d73b6da958bcd6#c958e5ce99374bbbd9922e9f71fe65a3>:0 \n  at Xamarin.Forms.Element.OnBindingContextChanged () <0x10582c410 + 0x000d3> in <978ec34c5c9c4c4eb3d73b6da958bcd6#c958e5ce99374bbbd9922e9f71fe65a3>:0 \n  at Xamarin.Forms.View.OnBindingContextChanged () <0x1059065d4 + 0x00053> in <978ec34c5c9c4c4eb3d73b6da958bcd6#c958e5ce99374bbbd9922e9f71fe65a3>:0 \n  at Xamarin.Forms.ContentView.OnBindingContextChanged () <0x10581bca0 + 0x00013> in <978ec34c5c9c4c4eb3d73b6da958bcd6#c958e5ce99374bbbd9922e9f71fe65a3>:0 \n  at Xamarin.Forms.BindableObject.BindingContextPropertyChanged (Xamarin.Forms.BindableObject bindable, System.Object oldvalue, System.Object newvalue) <0x1057f4940 + 0x00047> in <978ec34c5c9c4c4eb3d73b6da958bcd6#c958e5ce99374bbbd9922e9f71fe65a3>:0 \n  at Xamarin.Forms.BindableObject.SetValueActual (Xamarin.Forms.BindableProperty property, Xamarin.Forms.BindableObject+BindablePropertyContext context, System.Object value, System.Boolean currentlyApplying, Xamarin.Forms.Internals.SetValueFlags attributes, System.Boolean silent) <0x1057f44b8 + 0x001e7> in <978ec34c5c9c4c4eb3d73b6da958bcd6#c958e5ce99374bbbd9922e9f71fe65a3>:0 \n  at Xamarin.Forms.BindableObject.SetValueCore (Xamarin.Forms.BindableProperty property, System.Object value, Xamarin.Forms.Internals.SetValueFlags attributes, Xamarin.Forms.BindableObject+SetValuePrivateFlags privateAttributes) <0x1057f4074 + 0x0020f> in <978ec34c5c9c4c4eb3d73b6da958bcd6#c958e5ce99374bbbd9922e9f71fe65a3>:0 \n  at Xamarin.Forms.BindableObject.SetValue (Xamarin.Forms.BindableProperty property, System.Object value, System.Boolean fromStyle, System.Boolean checkAccess) <0x1057f3d94 + 0x0008b> in <978ec34c5c9c4c4eb3d73b6da958bcd6#c958e5ce99374bbbd9922e9f71fe65a3>:0 \n  at Xamarin.Forms.BindableObject.set_BindingContext (System.Object value) <0x1057f2170 + 0x00047> in <978ec34c5c9c4c4eb3d73b6da958bcd6#c958e5ce99374bbbd9922e9f71fe65a3>:0 \n  at InspectFlow.Core.Views.ChecklistView..ctor (InspectFlow.Core.ViewModels.ChecklistViewModel vm) <0x104a59970 + 0x0003f> in <5cf03c4fb6f1467395ccd8cb7e4984eb#c958e5ce99374bbbd9922e9f71fe65a3>:0 \n  at InspectFlow.Core.ViewModels.ChecklistPageViewModel..ctor (System.Int64 id, InspectFlow.WebAPI.Models.Checklist checklist, System.String projectName, System.Boolean showObservation, System.Boolean showReady4Review) <0x104a8dc10 + 0x0013b> in <5cf03c4fb6f1467395ccd8cb7e4984eb#c958e5ce99374bbbd9922e9f71fe65a3>:0 \n  at InspectFlow.Core.ViewModels.MainViewModel.SetProjectChecklistContent (System.Int64 id, InspectFlow.WebAPI.Models.Checklist checklist, System.String name, System.Boolean animate) <0x104a92210 + 0x000af> in <5cf03c4fb6f1467395ccd8cb7e4984eb#c958e5ce99374bbbd9922e9f71fe65a3>:0 \n  at InspectFlow.Core.ViewModels.MainViewModel.SetSelectedForm (InspectFlow.Core.Models.FormObservable value) <0x104a1f120 + 0x0051b> in <5cf03c4fb6f1467395ccd8cb7e4984eb#c958e5ce99374bbbd9922e9f71fe65a3>:0 ",
    "innerExceptions": [
      {
        "type": "System.IndexOutOfRangeException",
        "message": "Index was outside the bounds of the array.",
        "stackTrace": "  at Markdig.Markdown..cctor () <0x105c661c8 + 0x00140> in <b897da1c1c90426cb39ac42aa4f60a7d#c958e5ce99374bbbd9922e9f71fe65a3>:0 ",
        "wrapperSdkName": "appcenter.xamarin"
      }
    ],
    "wrapperSdkName": "appcenter.xamarin"
  },
  "appId": "6942a61f-f809-45af-a573-17d96e096c34",
  "installId": "5F004921-CB96-4EA1-A5D7-140ACC10788D",
  "isTestMessage": false,
  "timestamp": "2021-03-31T16:30:19.061Z",
  "sid": "cef443a2-9f07-4122-a1d2-d12c05571f9b",
  "userId": "5648825477758976 (Steve Hatch)",
  "device": {
    "sdkName": "appcenter.ios",
    "sdkVersion": "4.1.1",
    "wrapperSdkVersion": "4.2.0",
    "wrapperSdkName": "appcenter.xamarin",
    "model": "iPhone12,5",
    "oemName": "Apple",
    "osName": "iOS",
    "osVersion": "14.4.2",
    "osBuild": "18D70",
    "locale": "en_US",
    "timeZoneOffset": -300,
    "screenSize": "2688x1242",
    "appVersion": "2.50",
    "appBuild": "25",
    "appNamespace": "com.huvrdata.inspectflow2",
    "wrapperRuntimeVersion": "12.6.0"
  }
}

**Comment by MihaZupan** [comment]
> The type initializer for 'Markdig.Markdown' threw an exception

> "type": "System.IndexOutOfRangeException",

So from the code, the only thing I can think of is:

https://github.com/xoofx/markdig/blob/203cfd6508d4f8fca510edd2f66f229ada2c25ad/src/Markdig/Markdown.cs#L22

That hasn't changed in years tho

**Comment by xoofx** [comment]
> After upgrading from 0.23 to 0.24 our app runs fine in debug but crashes in release. Our QA department tells me it's only in iOS if that helps

We can't really investigate more than what @MihaZupan did above. It could be for example a code stripping as part of your build that is removing the `AssemblyFileVersionAttribute` for example, so I don't think it is an issue in Markdig.

**Comment by jimiatnymbl** [comment]
Just thought I'd add our experience as well.  We just upgraded our Xamarin.Forms app to Xamarin Forms 5 (and all of the NuGet packages were brought up to their latest versions).

We also experienced this crash and also *only* on iOS and only a release build.

The only fix was downgrading to 0.23 (we changed nothing else).
