### ISSUE TITLE
What is the best way is to determine, if the syntax that I would like to add is not conflicting with any other existing extension. 

### ISSUE THREAD

**Issue by olenitsj** [xoofx/markdig#537]
I am working on an extension and I would like to know if my syntax won't be conflicting with any other extension.
What is the best way to achieve that?

**Comment by xoofx** [comment]
There is no easy way outside of the project itself as you figured out in #538.
We would have to ship the tests as a separate NuGet package in order to support that scenario.

**Comment by MihaZupan** [comment]
If you have concrete examples of syntax in mind, you could ask for feedback on the https://talk.commonmark.org/ forum

**Comment by olenitsj** [comment]
Thank you for your responses I will look into the proposed solution.

Would the following spec configuration in SpectFileGen result in enabling ALL extensions?
     
new Spec("Forms", "FormsSpecs.md", "advanced+pipetables+gfm-pipetables+footnotes+attributes+emphasisextras+hardlinebreak+gridtables+customcontainers+definitionlists+emojis+abbreviations+listextras+mathematics+bootstrap+figures+medialinks+smartypants+autoidentifiers+tasklists+diagrams+nohtml+yaml+autolinks+jiralinks+globalization+forms"),
