### ISSUE TITLE
Isn't it support the anchor?

### ISSUE THREAD

**Issue by devncore-james** [xoofx/markdig#541]
`code` (convert to html)
```csharp
var pipline = new MarkdownPipelineBuilder().UsePipeTables().UseGridTables()
    .UseAdvancedExtensions().UseEmojiAndSmiley().Build();
string html = Markdig.Markdown.ToHtml(Markdown, pipline);
```

`Markdown` 
```markdown
[header](#1-header) 
# 1. Header
```

`HTML`
```html
<a href="1-header">1. Header</h1>

<h1 id="header">1. Header</h1>
```

Is there a way to accurately convert id? Or did I miss something?

**Comment by xoofx** [comment]
The default mode does not support letters. You should use [AutoIdentifierOptions.GitHub](https://github.com/xoofx/markdig/blob/0a0040450fd4f774dacc71bcaf0ed1651a792cea/src/Markdig/Extensions/AutoIdentifiers/AutoIdentifierOptions.cs#L35-L38). The doc doesn't explain the difference but the code is [here](https://github.com/xoofx/markdig/blob/0a0040450fd4f774dacc71bcaf0ed1651a792cea/src/Markdig/Helpers/LinkHelper.cs#L22-L111) (`Urilize` vs `UrilizeAsGfm`)
