### ISSUE TITLE
what's the pattern of adding <p> tag to list item?

### ISSUE THREAD

**Issue by Edward-Chen-CN** [xoofx/markdig#546]
Sometime the list item surrounded by `<p>` tag, sometime the value rendered inline. I would like to know what the pattern of adding the `<p>` tag to the list item or is there any way I can set it always surrounded by `<p>` tag

`<li>content 1</li>`
`<li><p>content 2</P></li>`

**Comment by xoofx** [comment]
The difference is between Loose and Tight lists as described in the [specs](https://spec.commonmark.org/0.29/#lists)

> _A list is loose if any of its constituent list items are separated by blank lines, or if any of its constituent list items directly contain two block-level elements with a blank line between them. Otherwise a list is tight. (The difference in HTML output is that paragraphs in a loose list are wrapped in `<p>` tags, while paragraphs in a tight list are not.)_
