### ISSUE TITLE
Problem with rendering Local Image Path with whitespaces to HTML

### ISSUE THREAD

**Issue by 1001binary** [xoofx/markdig#550]
Hello,

I had problem with rendering **local image Path** with whitespace to HTML. It didn't work. After that, I tried to replace whitespaces in path by %20. It worked fine.

Problem :x:
```
string text = "This is image: ![Image Alt Text](\\server\Image Files\test.png)"
Console.WriteLine(Markdig.Markdown.ToHtml(text));
// Output: "<p>This is image: ![Image Alt Text](\server\Image Files\test.png)</p>"
```

Worked :heavy_check_mark:
```
string text = "This is image: ![Image Alt Text](\\server\Image%20Files\test.png)"
Console.WriteLine(Markdig.Markdown.ToHtml(text));
// Output: "<p>This is image: <img src=""%5Cserver%5CImage%20Files%5Ctest.png"" alt=""Image Alt Text"" /></p>"
```

For image URL, it worked fine for both cases.

Best regards.

**Comment by MihaZupan** [comment]
This is essentially [Example 485 of the spec](https://spec.commonmark.org/0.29/#example-485):

> The destination can only contain spaces if it is enclosed in pointy brackets

So to make the above example work: `This is image: ![Image Alt Text](<\\server\Image Files\test.png>)`

**Comment by 1001binary** [comment]
Sorry for my late response and also thank you for your response.

Even though it's correct as the spec, for MarkdownTextBlock in UWP I found something incompatible such as rendering path. I had to adapt this in UWP.
