### ISSUE TITLE
Using multiple "Opening Characters" for extension

### ISSUE THREAD

**Issue by Z3roCoder** [xoofx/markdig#552]
Hello!

I have written a few Extensions so far, but they all relied on a single trigger symbol / character.
Now I wanted to ask if it was possible to perhaps use something like "Issue xxx" where as "Issue" is the triggerword instead of a "#" and takes teh following alphanumerical string (with or without whitespace) and processes/parses it.
As far as I know, OpeningCharacters is just an array of characters with each character in the array acting as the trigger individually.

Is there a way to achieve something like "#1234 acts the same as Issue 1234"?

**Comment by xoofx** [comment]
Yes, you need to list the exact characters, but if it is just 1-9, it's just 9 characters you have to put.

For example the Jira Link extension is putting the whole alphabet as an opening character ([here](https://github.com/xoofx/markdig/blob/27f625f15b0007f7c7d3210d58de4ba074816df7/src/Markdig/Extensions/JiraLinks/JiraLinkInlineParser.cs#L21-L27)
