### ISSUE TITLE
How to create wysiwyg-like editor using Markdig?

### ISSUE THREAD

**Issue by assopri** [xoofx/markdig#557]
I need MD editor to utilize in my .NET application. It should work in the similar way to https://stackedit.io/app# . I mean I must see stylization in editor pane as well: https://screencast-o-matic.com/watch/cr1iiOVhpT6 (short video to show that I mean). Any Markdig based solutions for this issue?

**Comment by xoofx** [comment]
I know that https://markdownmonster.west-wind.com/ is using Markdig. Not sure there are OSS options though.
