### ISSUE TITLE
Installed NuGet throws System.IO.FileNotFoundException

### ISSUE THREAD

**Issue by MarkoKvyk** [xoofx/markdig#558]
Creating classlibrary and trying to install `Markdig`.

[![enter image description here][1]][1]

I can use usings in code, but I'm trying to start debugging and it throws it:

[![enter image description here][2]][2]

link to library.
https://github.com/xoofx/markdig

Here is my .csproj

```
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net5.0</TargetFramework>
    <RootNamespace>Kvyk.Telegraph.Markdown</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Kvyk.Telegraph" Version="1.0.2" />
    <PackageReference Include="Markdig" Version="0.25.0" />
  </ItemGroup>

</Project>
```

https://stackoverflow.com/questions/68070423/installed-nuget-throws-system-io-filenotfoundexception

  [1]: https://i.stack.imgur.com/ovGdr.png
  [2]: https://i.stack.imgur.com/SpWY5.png

**Comment by xoofx** [comment]
Just tried and it is working on my machine, it's working on the CI and it's working also for many users, with 2000+ download per day, we would get a substantial number of issues like that if Markdig was not working like you describe.

So you might have something wrong on your machine. Maybe try to setup a global.json which restrict to net5.0 SDK and/or remove any superfluous dotnet SDK installed. Try to install a new version of dotnet SDK 5.0. Cleanup maybe your NuGet cache folders...etc. Have you installed a preview version of VS like VS 2022? That could break things like that... but it could be anything, even a global env variable that is messing with msbuild. You can investigate yourself such issues by checking the log of msbuild...etc.

**Comment by MarkoKvyk** [comment]
I've tryed to create new class library and install Markdig here. It works good.
Also I've downloaded my repo in new folder, tryed to add it, and have the same error.

Do you have any ideas about problem? I'm stacked with it. Probably you can download my repo https://github.com/MarkoKvyk/Telegraph/tree/development
(development branch), create classlibrary here and add Markdig to it and watch what's wrong

**Comment by MarkoKvyk** [comment]
I found the problem. Problem in my Test project. For some reasones it doesnt work well and dont install packages. How to fix it I have no idea. If you had issue like that, please help me. Also you can check it in my repo https://github.com/MarkoKvyk/Telegraph/tree/development
(development branch)

**Comment by MarkoKvyk** [comment]
I found the solution. In my test project were added dublicated references. I`ve created net test project for project I need to test an it works now.
