### ISSUE TITLE
0.24 and later crashes on Xamarin iOS release build. Not debug build.

### ISSUE THREAD

**Issue by conceptworld** [xoofx/markdig#564]
When calling Markdown.ToHtml(), markdig crashes in release/distribution builds. But on debug it works.
I had to revert back to 0.23. Thanks to this page for giving me a hint: https://www.gitmemory.com/issue/xoofx/markdig/536/820772305

There is not special html I am using. Even empty string or plain text without markdown crashes it.

And with further testing, it appears that this issue is seen only in physical device and not in simulator.

Thanks.

**Comment by xoofx** [comment]
It's an AOT problem Xamarin iOS side (e.g their mono AOT compiler) and unlikely in Markdig itself.

**Comment by MihaZupan** [comment]
@conceptworld @jimiatnymbl @stevehatch I would suggest filing an issue with Xamarin as this is likely some sort of linker bug on their side. If you are able to provide a repro they should be able to triage it.

Something you could try is to build Markdig yourself and remove [this line](https://github.com/xoofx/markdig/blob/cdd4b40469bc62258ede879fb7ed38237ef8a2fb/src/Markdig/Markdown.cs#L22) to see if the problem still reproduces. If it requires an actual device, I'm afraid I can't validate the change myself.
