### ISSUE TITLE
Hyphen on a new line doesn't return correct html

### ISSUE THREAD

**Issue by conceptworld** [xoofx/markdig#566]
If I send the following plain text to Markdown.ToHtml:

First  line\nSecond line\n-

(Notice that there is single hyphen in a new line above)

Then the method returns

&lt;h2&gt;First lineSecond line&lt;/h2&gt;

There are no &lt;br&gt; for new lines and h2 is applied to all the lines above the hyphen.

This is a major issue as many users use hyphens for simple demarcation.

Also I don't think single hyphen should work this way. 2 or 3 hyphens should result in markdown formatting.

Thanks.

**Comment by xoofx** [comment]
All CommonMark implementation should follow the same behavior (unless we broke something recently in markdig) as shown on [babelmark](https://babelmark.github.io/?text=First+line%0ASecond+line%0A-%0A%0A)

> There are no <br> for new lines and h2 is applied to all the lines above the hyphen.
> This is a major issue as many users use hyphens for simple demarcation.
> Also I don't think single hyphen should work this way. 2 or 3 hyphens should result in markdown formatting.

This is the specs we are following https://spec.commonmark.org/0.29/#thematic-breaks
