### ISSUE TITLE
Markdown.ToHtml does not work.

### ISSUE THREAD

**Issue by HenreyMine** [xoofx/markdig#569]
I have simple program:
```
var mdText = "<!DOCTYPE html>`EntityRecognitionInfo`";
var pipeline = new MarkdownPipelineBuilder().UseAdvancedExtensions().Build();
Console.WriteLine(Markdown.ToHtml(mdText, pipeline));
```
But the original string doesn't change in any way. 
I was expecting the following text in the output:
`<!DOCTYPE html><code>EntityRecognitionInfo</code>`
Is it a bug?

**Comment by xoofx** [comment]
> Is it a bug?

No, it's per the CommonnMark [specs](https://spec.commonmark.org/0.29/#html-blocks). An HTML block will escape the entire current line and consider the following as HTML.

See the behavior of other [markdown engines](https://babelmark.github.io/?text=%3C!DOCTYPE+html%3E%60EntityRecognitionInfo%60).
