### ISSUE TITLE
AutoLinkOptions.OpenInNewWindow should use target=_blank

### ISSUE THREAD

**Issue by lajjne** [xoofx/markdig#571]
Setting `AutoLinkOptions.OpenInNewWindow=true` adds `target=blank` to the links.  I'm assuming this is a typo and should be changed to `target=_blank`. This also seems to be the case for JiraLinks which should probably also be changed to `target=_blank` .

**Comment by MihaZupan** [comment]
Nice catch, you're right - it should be `_blank`
