### ISSUE TITLE
Is there a way to render links in such a way that they will open in new window ?

### ISSUE THREAD

**Issue by macmarek** [xoofx/markdig#577]
Hey,
I'm trying to make sure that all links generated by Markdig are opening in a new browser window. Is there a way to achieve this?

Example:
I'd like
```[stackoverflow.com](https://stackoverflow.com/)```

to be rendered as
```<a href="https://stackoverflow.com/" target="_blank">stackoverflow.com</a>```

instead of
```<a href="https://stackoverflow.com/">stackoverflow.com</a>```

**Comment by MihaZupan** [comment]
If you only care about auto links (links that just appear in the text and arent defined as `[foo](url)`), you can set the `OpenInNewWindow` flag:
```c#
var pipeline = new MarkdownPipelineBuilder()
    .UseAutoLinks(new AutoLinkOptions { OpenInNewWindow = true })
    .Build();
```

To get the same effect on all links, the easiest way is probably to post-process the document and add the attributes.

```c#
MarkdownDocument document = Markdown.Parse(markdown, pipeline);

foreach (LinkInline link in document.Descendants<LinkInline>())
{
    link.GetAttributes().AddPropertyIfNotExist("target", "_blank");
}

foreach (AutolinkInline link in document.Descendants<AutolinkInline>())
{
    link.GetAttributes().AddPropertyIfNotExist("target", "_blank");
}

string html = document.ToHtml(pipeline);
```

**Comment by macmarek** [comment]
Thanks a lot. Works like a charm!
