### ISSUE TITLE
Not rendering list properly

### ISSUE THREAD

**Issue by iRowin02** [xoofx/markdig#581]
I'm trying to create a markdown editor which so far has gone pretty successful, 
the only problem I have right now is that whenever I try to make a list.
This list doesn't properly show up. Even though when I check to inspect elements it does show up as a list.

My pipeline is as followed:
```cs
pipeline = new MarkdownPipelineBuilder()
                   .UseAdvancedExtensions()
                   .UseSyntaxHighlighting()
                   .UseListExtras()
                   .UseAutoIdentifiers()
                   .UseTaskLists()
                   .UseAbbreviations()
                   .UseGenericAttributes()
                   .UseBootstrap()
                   .UseSoftlineBreakAsHardlineBreak()
                   .Build();

            if (pipeline != null)
            {
                if (input != null)
                {
                    output = Markdown.ToHtml(input, pipeline);
                }
            }
            return output;
```
This is my input
![image](https://user-images.githubusercontent.com/13496569/148554533-c4f980f4-ce5f-425d-8661-25d4641f6007.png)

This is how it shows when parsed
![image](https://user-images.githubusercontent.com/13496569/148554666-fcf56473-8f06-467b-ac7e-4488efd01b15.png)

This is what it shows inside my inspect element
![image](https://user-images.githubusercontent.com/13496569/148554727-22ffdc9f-9df5-4255-8d3e-300c6b4bc5a4.png)

Yet I'm missing the dots that should be in front of this.

**Comment by xoofx** [comment]
> Yet I'm missing the dots that should be in front of this.

Not sure to follow, what is the `dots` here? Sounds more like a CSS issue on your side with an incorrect rendering of `<li>` items.

**Comment by iRowin02** [comment]
> > Yet I'm missing the dots that should be in front of this.
> 
>  what is the `dots` here? 

After googling a bit more, I found that they're called 'Bullet points'. Though I checked in my CSS if I manipulated the behavior of <li> classes. But this isn't the case.

**Comment by xoofx** [comment]
For sure, the HTML output looks correct from Markdig , so I don't think it is a Markdig issue but definitely a non correct usage of CSS.

**Comment by iRowin02** [comment]
I'm not really the best at CSS, so I haven't gotten a clue what could be the cause. Or how to check, but thanks for pointing out. I'll see what I can do.

**Comment by iRowin02** [comment]
Well, I fixed it by overwriting some stuff in the CSS. I can now consider myself a CSS god.
