### ISSUE TITLE
Package ID Prefix Issue

### ISSUE THREAD

**Issue by wbaldoumas** [xoofx/markdig#582]
I am currently working on [a small Markdig extension](https://github.com/wbaldoumas/markdig-colorcode) that adds markdown syntax highlighting by leveraging [ColorCode-Universal](https://github.com/CommunityToolkit/ColorCode-Universal), which is an updated version of [ColorCode](https://ripcode.net/p/colorcode). 

Unfortunately, I am running into an issue when trying to publish the library as a NuGet package:

```
error: Response status code does not indicate success: 409 (This package ID has been reserved. Please request access to upload to this reserved namespace from the owner of the reserved prefix, or re-upload the package with a different ID. Go to https://docs.microsoft.com/en-us/nuget/reference/id-prefix-reservation learn more about Package ID prefix reservation.).
```

I believe the issue is that "Markdig" is a reserved package ID prefix. Removing "Markdig" from the extension name will obscure its purpose from potential users of the library. Is there a path forward to being unblocked and publishing this extension as `Markdig.ColorCode`?

**Comment by xoofx** [comment]
>  Is there a path forward to being unblocked and publishing this extension as Markdig.ColorCode?

No there is no path apart prefixing your package with your own name as [everybody else](https://www.nuget.org/packages?q=markdig). There is one exception for `Markdig.Wpf`, but this package existed before the Markdig prefix was locked. Having a package like `Markdig.ColorCode` or any other packages would be very confusing as folks might think that it comes from this repo or it is supported in similar way.

**Comment by wbaldoumas** [comment]
Hey, thanks for your response and clarification. I'll find another package name that works and is still clear about what it does. I'll also be sure to adjust my repository name to match. 😄
