### ISSUE TITLE
In the Chinese environment, some specific symbols are not parsed correctly at the beginning and the end.

### ISSUE THREAD

**Issue by pengqian089** [xoofx/markdig#583]
Emphasis is placed on displaying certain text that will not be parsed correctly when starting and ending with `《` or `》`.

``` cs
var md = "不如人意的**《李茶的姑妈》**已经为开心麻花影业敲响警钟";
var pipeline = new MarkdownPipelineBuilder()
    .UsePipeTables()
    .UseTaskLists()
    .UseEmphasisExtras()
    .UseAutoIdentifiers()
    .UseAdvancedExtensions()
    .DisableHtml()
    .Build();
var html = Markdown.ToHtml(md, pipeline);
Console.WriteLine(html);
```
Result: 
``` html
<p>不如人意的**《李茶的姑妈》**已经为开心麻花影业敲响警钟</p>
```

Expected:
```html
<p>不如人意的<strong>《李茶的姑妈》</strong>已经为开心麻花影业敲响警钟</p>
```

I found that Github is not parsed correctly either.

``` markdown
**《李茶的姑妈》**
**李茶的姑妈**

**《strong》**
**strong**
```
------
**《李茶的姑妈》**
**李茶的姑妈**

**《strong》**
**strong**

Sorry, my English is very poor.
I am still working on my English, but it's getting better.
I use it every day now.

**Comment by pengqian089** [comment]
> It's not so much the `《 》` characters, but that emphasis requires a space before it:
> 
> ```
> a**《text》**b
> 
> a **《text》** b
> ```
> 
> See [babelmark](https://babelmark.github.io/?text=a**%E3%80%8Atext%E3%80%8B**b%0A%0Aa+**%E3%80%8Atext%E3%80%8B**+b) - most CommonMark parsers behave the same way as Markdig

Thanks.
Can this be considered a bug?
I can be parsed correctly when I use Typora.

**Comment by MihaZupan** [comment]
It is not a bug - Markdig is behaving according to the CommonMark specification here.

While CommonMark allows intraword emphasis like `foo**bar**baz`, it has restrictions when the emphasis is preceded/followed by punctuation.

See [left-flanking-delimiter-run](https://spec.commonmark.org/0.30/#left-flanking-delimiter-run) from the spec.

> A left-flanking delimiter run is a delimiter run that is (1) not followed by Unicode whitespace, and either (2a) not followed by a Unicode punctuation character, or (2b) followed by a Unicode punctuation character and preceded by Unicode whitespace or a Unicode punctuation character. For purposes of this definition, the beginning and the end of the line count as Unicode whitespace.

Note `(2b) followed by a Unicode punctuation character and preceded by Unicode whitespace or a Unicode punctuation character`. In your case, `《` falls under the `Open Punctuation` Unicode category, so CommonMark requires that emphasis be preceded by a whitespace character.

Similar holds for `》` that falls under `Close Punctuation`. The [right-flanking-delimiter-run](https://spec.commonmark.org/0.30/#right-flanking-delimiter-run) definition requires that it is followed by either a whitespace / another punctuation character.

Following these rules, the following are valid:
```
**《text》**
a **《text》**
a **《text》**
a **《text》** b
a **《text》**.
```

But
```
a**《text》**b
```

is not.

> I can be parsed correctly when I use Typora.

Typora may be using a more relaxed definition of Markdown, but isn't compliant to the spec here.

**Comment by pengqian089** [comment]
Thank you for your reply and answer.

I'll get to work on those characters next.
