### ISSUE TITLE
Coloring support for code

### ISSUE THREAD

**Issue by rdmzkn** [xoofx/markdig#594]
Is there any colouring support for  code tag ? 

I use the latest version and colouring updates are not generated in html for code sections in md files.

**Comment by xoofx** [comment]
In my experience, I have been using `prism.js` with markdig without changing anything, used on my blog post and on https://kalk.dev/ and it works very well.

Also see [some third party extensions](https://github.com/xoofx/markdig#third-party-extensions) that are proposing syntax highlighting
