### ISSUE TITLE
Replacing Contents of HtmlBlock / HtmlInline

### ISSUE THREAD

**Issue by damageboy** [xoofx/markdig#599]
Hi,
I'm looking for a cookbook like recipe for how is the "right" way, as far as markdig is concerned for doing markdown transformations.

Namely, I'm trying to concert a `.md` file to a `.mdx` file using markdig.

One of the relatively minor challenges in this process is converting `style="a: b;c: d"` html attributes to `style={{a: b, c: d}}`.

Generally speaking, making such changes in a "living" MarkdownDoc class is not very well documented, or I'm just reading the wrong documents.

Could anyone chart the path of least resistance when it comes to such challenges?

**Comment by xoofx** [comment]
> I'm looking for a cookbook like recipe for how is the "right" way, as far as markdig is concerned for doing markdown transformations.

It depends on what you want to do. If it is to re-emit markdown documents or to still transform it to a pseudo-HTML content? The later is usually the easiest.

But the former, depending on your processing need, can be done by processing Markdown syntax tree via e.g [MarkdownObject.Descendants](https://github.com/xoofx/markdig/blob/9bbf6855e1df877e7fd472a810633b44e40a9be9/src/Markdig/Syntax/MarkdownObjectExtensions.cs#L240)

If you need to write a different output, you might have to write a custom renderer or you can overwrite an existing one (e.g HtmlRenderer). You can see the code [here](https://github.com/xoofx/markdig/tree/master/src/Markdig/Renderers) and despite the lack of doc, it should not be too difficult to figure out how to write a new one or overwrite a new one.
