### ISSUE TITLE
Footnote vs Endnote

### ISSUE THREAD

**Issue by anders-eriksson** [xoofx/markdig#616]
There seems to be some conceptual confusion between **footnote** and **endnote**

If I use [^1]
[^1]: this is a footnote or is it?

Then the note will be shown at the last page, i. e. an **endnote**

Is there someway to create a footnote, that will show at the page that it is created?

**Comment by xoofx** [comment]
So the footnote extension in markdig is following what most other markdown engine are doing (see [here](https://babelmark.github.io/?text=Here+is+a+footnote%5B%5E1%5D.+%0A%0A%5B%5E1%5D%3A+Footnote+1+text)) and taken initially from [php-markdown: footnotes](https://michelf.ca/projects/php-markdown/extra/#footnotes)

Also, an HTML page is originally and conceptually... a single page, hence why the term footnote is yes, an endnote, but you will see little difference in HTML discussions about these concepts.

So when you say:

> Is there someway to create a footnote, that will show at the page that it is created?

What is a page here? When you print it? I can see that there is [CSS Paged Media Module Level 3](https://www.w3.org/TR/css-page-3/) that was introduced recently, but it is a CSS level concept, not sure what do you propose to handle it at HTML level? Have you seen this in other markdown implementation? (it would need to maximize compatibility)

Lastly, just to make sure about the expectations here, I have personally no time to implement new features in markdig, so even if you come with a good proposal, you will have to make a pull request to make it happen.

**Comment by andermikael** [comment]
I'm using Markdown Monster and are exporting it to a PDF.
It would be nice to get a footnote, but...

Thanks for all the work you have put in!
