### ISSUE TITLE
Markdig.dll flagged as Trojan

### ISSUE THREAD

**Issue by av-guy** [xoofx/markdig#617]
Hi,

I am sorry if this is an issue that has already been resolved or if this is the wrong place to post this, but MalwareBytes is flagging Markdig.dll as a Trojan. Any idea what might be causing this?

**Comment by MihaZupan** [comment]
Nothing we can do about that. [VirusTotal](https://www.virustotal.com/gui/file/ec7e4e50ea82877b698838522e0610f8090ad13e62469b292049ef6612894230/detection) doesn't show any hits, so maybe check if your AV is up to date?

**Comment by av-guy** [comment]
Will do. I'll close out the issue for now and look into it on my own. Thanks for the reply.
