### ISSUE TITLE
Render code snippet from a file

### ISSUE THREAD

**Issue by rafaelarnosti** [xoofx/markdig#618]
Hello,

I'd like to know if it's possible to render using markdig, a CodeSnippet from other file, like the exemple bellow:

```csharp
    ~\View\Errorpage.cshtml
```

**Comment by xoofx** [comment]
I'm not sure to understand: in your example above, it is a cshtml file, not a markdown file. What is the link? Do you mean that you would like to include markdown files in other markdown files?

**Comment by rafaelarnosti** [comment]
I have a cshtml file and I want to put the path in my markdown and when it render the code inside the file will be render together with my markdown

**Comment by xoofx** [comment]
So it's possible, you could maybe use the link syntax with a special character in the label e.g `[@code](~\View\Errorpage.cshtml)`

Then, you can parse the document, get all the links (e.g `doc.Descendants<LinkInline>()`) and replace them with some `FencedCodeBlock` before rendering to HTML.
