### ISSUE TITLE
Is There A Way To Configure ToHtml For Not Adding '\n' At The End of Every Converted String?

### ISSUE THREAD

**Issue by napierbw51** [xoofx/markdig#635]
Currently using the Markdig.Markdown.ToHtml adds a '\n' character at the end of every string that is converted. This can be shown using the C# Online Compiler:
![image](https://user-images.githubusercontent.com/23728353/166942651-ee26f86b-e0e9-4f7e-917c-c5438a2d23b1.png)

Is there a way to configure ToHtml so that the new line character isn't added? Currently, in my project I'm using .TrimEnd('\n') to remove it but I'm looking for a more graceful solution.

**Comment by xoofx** [comment]
> Is there a way to configure ToHtml so that the new line character isn't added?

No. The code changes to support this would be significantly more involving than the `.TrimEnd('\n')` on the final string.
