### ISSUE TITLE
Markdown outline to html question

### ISSUE THREAD

**Issue by pickzhu** [xoofx/markdig#639]
Is it now supported to bring an outline when converting from Markdown to html?

**Comment by xoofx** [comment]
I don't understand what is an outline in your question. Could you give an example?

**Comment by pickzhu** [comment]
That is, can the directory of the md file be generated?

**Comment by xoofx** [comment]
Sorry, I still don't understand your question. Markdig is a library to transform a Markdown string into a HTML string. It doesn't have any knowledge about folder structure. It is application specific and should be handled in your lib/app.
