### ISSUE TITLE
Setting to open external URL's in new browser tab

### ISSUE THREAD

**Issue by jasell** [xoofx/markdig#641]
In our Markdig implementation we would like all external links to open in a new browser tab.
After some investigation we found that Markdig (advanced) can do this with below syntax.

```
[Open Markdig in new tab](https://github.com/xoofx/markdig){target="_blank"}
```
It would be nice if we can set up Markdig to always render external links with this addition.
This way users do not need to add or risk forgetting it.

**Comment by MihaZupan** [comment]
See https://github.com/xoofx/markdig/issues/577#issuecomment-984737406

**Comment by jasell** [comment]
Super, exactly what I was looking for, closing...
