### ISSUE TITLE
Some markdown causes Exception during the convert

### ISSUE THREAD

**Issue by laolarou726** [xoofx/markdig#643]
Some of the markdown documents will cause the converter to throw System.Xml.XmlException("")

Usage:
<img width="324" alt="image" src="https://user-images.githubusercontent.com/25716486/172477513-013cef84-4994-4305-9ff8-2dd4f5b96be2.png">

Example:
[Untitled-1.md](https://github.com/neolithos/NeoMarkdigXaml/files/8856423/Untitled-1.md)

**Comment by MihaZupan** [comment]
Please file an issue with https://github.com/neolithos/NeoMarkdigXaml as this doesn't look like a Markdig error
