### ISSUE TITLE
The converted content is incorrect

### ISSUE THREAD

**Issue by colindcli** [xoofx/markdig#647]
using System;

public class Program
{
	public static void Main()
	{
		var result = Markdig.Markdown.ToHtml("**This is:**a text with some*emphasis*");
		Console.WriteLine(result); // prints: <p>This is a text with some <em>emphasis</em></p>
	}
}

![err](https://user-images.githubusercontent.com/3311217/177124683-fb746b3a-a47f-4155-b854-7890bf4922b5.png)

**Comment by xoofx** [comment]
I haven't the character `：` before `**123`, but it is likely considered as a space or unicode punctuation character and so, as stated by the spec, the right `**` is not going to be detected as a right flanking delimiter run.

> A [right-flanking delimiter run](https://spec.commonmark.org/0.30/#right-flanking-delimiter-run) is a [delimiter run](https://spec.commonmark.org/0.30/#delimiter-run) that is (1) not preceded by [Unicode whitespace](https://spec.commonmark.org/0.30/#unicode-whitespace), and either (2a) not preceded by a [Unicode punctuation character](https://spec.commonmark.org/0.30/#unicode-punctuation-character), or (2b) preceded by a [Unicode punctuation character](https://spec.commonmark.org/0.30/#unicode-punctuation-character) and followed by [Unicode whitespace](https://spec.commonmark.org/0.30/#unicode-whitespace) or a [Unicode punctuation character](https://spec.commonmark.org/0.30/#unicode-punctuation-character).

**Comment by colindcli** [comment]
.

**Comment by tats-u** [comment]
For Chinese text (doesn't work for your example here):

- #890
