### ISSUE TITLE
Headline IDs without reserved-CSS characters

### ISSUE THREAD

**Issue by Mrks83** [xoofx/markdig#656]
Markdig generates IDs that might contain a `.` character. This is not optimal (see https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/id#sect2).

Would be nice to be able to escape `.` (and other characters reserved in css `+`, `~`, `!`), too.

![image](https://user-images.githubusercontent.com/5073749/187362236-047979fe-730e-43cb-a08f-d201f60e64ca.png)

**Comment by xoofx** [comment]
I think that originally, the default generated IDs was following pandoc (see the output [here](https://babelmark.github.io/?text=%23%23+Release+1.1))

But you can configure the AutoIdentifier extension directly and use `AutoIdentifierOptions.GitHub` instead.

**Comment by Mrks83** [comment]
Thanks for the `AutoIdentifierOptions.GitHub` hint, that helps and works exactly as proposed.
