### ISSUE TITLE
Bump the Mermaid version

### ISSUE THREAD

**Issue by selvavm** [xoofx/markdig#657]
Hi,

Thanks for your contribution. I could notice that Mermaid 9.1.2 is being used and it would be nice if this is bumped to the latest version (9.1.6). 

Thanks again.

**Comment by MihaZupan** [comment]
Where do you see that? [This](https://github.com/xoofx/markdig/blob/bce4b70dc69803b9f45f00c542f6715bc6934981/src/Markdig/Extensions/Diagrams/DiagramExtension.cs#L26) is the only reference to Mermaid I can see in Markdig.

**Comment by xoofx** [comment]
Markdig does not use or reference any mermaid library. You might redirect your request to the repository where Markdig is used and you noticed this reference.
