### ISSUE TITLE
Add identifier to blockquote

### ISSUE THREAD

**Issue by CayasSoftware** [xoofx/markdig#659]
I would like to ask a question on how to add an identifier to a parent element like a blockquote.
My markdown looks like this:

    >test
    >
    >{#add}

Which will be rendert to the following HTML:

    <blockquote>
        <p>test</p>
        <p id="add"></p>
    </blockquote>

My assumption was that, because it is placed at the blockquote, the id will be attached there. Unfortunately it is attached to the p-element. I also tried it between > and test which attaches the id to the first paragraph tag.

My desired result should look like:

    <blockquote id="add">
        <p>test</p>
        <p></p>
    </blockquote>

Any advice on how to make it right would be great.

**Comment by xoofx** [comment]
You need to add it just before ([here](https://babelmark.github.io/?text=%7B%23add%7D%0A%3E+test%0A%3E)) (and need a while line before the attribute)

```md
{#add}
> test
```

**Comment by CayasSoftware** [comment]
Thank you very much. That was the only combination I had not tried.
