### ISSUE TITLE
When is HtmlEntityInline used?

### ISSUE THREAD

**Issue by Kation** [xoofx/markdig#662]
When start with a html element. There is a `HtmlBlock`.
```
<p>content</p>
```
When use html element mixed in a inline. There are two `HtmlInline`.
```
hello<b>world</b>.
```

And what markdown content will get a `HtmlEntityInline`?

**Comment by MihaZupan** [comment]
It's for things like `&lt;` or `&#34;`.
See https://www.w3schools.com/html/html_entities.asp
