### ISSUE TITLE
Custom Containers not rendering

### ISSUE THREAD

**Issue by Macadameane** [xoofx/markdig#669]
I recently tried to use this code to generate customer containers.  The headers and code fence work without problem.  Please let me know if I am doing something wrong:
```
    var pipeline = new MarkdownPipelineBuilder().UseAdvancedExtensions().Build();
    string tempDescription = @"
### Header 3
###### Header 6
Plain text

\```
Code fence
\```

:: Custom Span Container ::

:::
Custom Div Container
:::

";
    Description = Markdown.ToHtml(tempDescription);
```

The value of Description's output is below:
```
<h3>Header 3</h3>
<h6>Header 6</h6>
<p>Plain text</p>
<pre><code>Code fence
</code></pre>
<p>:: Custom Span Container ::</p>
<p>:::
Custom Div Container
:::</p>

```

**Comment by MihaZupan** [comment]
```diff
-Description = Markdown.ToHtml(tempDescription);
+Description = Markdown.ToHtml(tempDescription, pipeline);
```

Also note the difference between
```
:: Custom Span Container ::
```
and
```
::Custom Span Container::
```

See https://github.com/xoofx/markdig/blob/master/src/Markdig.Tests/Specs/CustomContainerSpecs.md#inline-custom-container

**Comment by Macadameane** [comment]
> ```diff
> -Description = Markdown.ToHtml(tempDescription);
> +Description = Markdown.ToHtml(tempDescription, pipeline);
> ```
> 
> Also note the difference between
> 
> ```
> :: Custom Span Container ::
> ```
> 
> and
> 
> ```
> ::Custom Span Container::
> ```
> 
> See https://github.com/xoofx/markdig/blob/master/src/Markdig.Tests/Specs/CustomContainerSpecs.md#inline-custom-container

Thanks a bunch.  I can't believe I forgot the overload.  I had tried with and without spaces and all sorts of things.

Thanks again.
