### ISSUE TITLE
Consider Non-breaking space (unicode spaces) as regular spaces for formatting

### ISSUE THREAD

**Issue by linkdotnet** [xoofx/markdig#675]
Hey,

if we have for example no-break spaces in ## (aka h2) elements, they don't get transform into `<h2>` elements because the library checks whether or not a "regular space" is used. A no-break space would be this: ` ` aka U+00A= (info here: https://www.compart.com/en/unicode/U+00A0)

Also GitHub does not consider them (whereas stackedit.io does recognize them).
## This should be an h2 element

If you have a Mac you can easily reproduce this with Option+SpaceBar, which produces the non-breaking space.

My request would be to include those characters as valid space-bars so that the above example would work.
I am not sure what the Markdown specification says about those "unicode spaces".

**Comment by MihaZupan** [comment]
I think GitHub may have stripped these characters from your example.
Do you mean if the heading is `"#\u00A0# foo"`? Or `## f\u00A0oo`?

For the former, that doesn't make sense as the input, just like it wouldn't make sense with regular spaces `# # foo`. The [spec](https://spec.commonmark.org/0.30/#atx-headings) doesn't mention that anything can be in between the `#` characters.

**Comment by linkdotnet** [comment]
The latter example `## f\u00A0oo`.
This example "should" work: `## My h2 title`.

You can copy&paste this into a website like [this](https://www.soscisurvey.de/tools/view-chars.php), which shows you non-printable characters.

**Comment by xoofx** [comment]
I think the spec says `##` must be followed by a space or a tab (not a unicode in the space category), so if you look at all other CommonMark compliant parser [here](https://babelmark.github.io/?text=%23%23%C2%A0foo) they don't parse `## foo` correctly either. 

So I would say, it's constrained as per spec, and so won't fix. Thoughts @MihaZupan ?

**Comment by MihaZupan** [comment]
> The opening sequence of # characters must be followed by spaces or tabs

My interpretation of the spec is that same as @xoofx.
If the spec intends for the broader interpretation of whitespace, it generally explicitly calls it `whitespace` or [`Unicode whitespace`](https://spec.commonmark.org/0.30/#unicode-whitespace-character).
Given that `commonmark.js` and GitHub don't support it either, I would also lean towards not changing anything in Markdig.

In any case, you can apply the fix on your side
```c#
markdown = markdown.Replace('\u00A0', ' ');
```

**Comment by linkdotnet** [comment]
Fair point. I guess for now we can close the issue. Thanks for your inputs!
