### ISSUE TITLE
.Net 7 support

### ISSUE THREAD

**Issue by dehghani-mehdi** [xoofx/markdig#699]
Could you add `.net7.0` to the targets and release the new version?

**Comment by MihaZupan** [comment]
While we don't mind newer versions, what does just bumping the TFM in a library get you?

**Comment by dehghani-mehdi** [comment]
So I can build my .net 7 project

**Comment by MihaZupan** [comment]
You can target Markdig from a .Net 7 project.
You'll end up using the 6.0 build of the library, which will work just as well as a 7.0 one would,since there are no platform specific changes made.

**Comment by xoofx** [comment]
Agreed with @MihaZupan, Markdig is supporting net6.0 which is compatible with net7.0. There is no need to provide a net7.0 version today as we are not using any new features introduced in net7.0.
