### ISSUE TITLE
Bug with TableCell Span range

### ISSUE THREAD

**Issue by Nintynuts** [xoofx/markdig#702]
I'm parsing files located here: `https://github.com/MicrosoftDocs/win32/tree/docs/desktop-src/direct3dhlsl`, so I can't modify the source file. I'm using the latest nuget release.

The table is a pipe table, not an HTML one, so I'm using `.UseAdvancedExtensions()` (and `.YamlFrontMatter()`) in my pipeline, to parse these markdown documents that contains pipe tables with some HTML in the cells. The problem is that the `MarkdownObject` span range is 10 characters too short, and doesn't include the entire cell contents.

This is the table row:
```md
| <span id="dest"></span><span id="DEST"></span>*dest*<br/> | \[in\] The address of the result of the operation.<br/> |
```
I get:
```html
<span id="dest"></span><span id="DEST"></span>*
```
Instead of:
```html
<span id="dest"></span><span id="DEST"></span>*dest*<br/>
```

To fix this, I checked the inlines of the paragraph block and found that the '*dest*' bit was just '*', and the containing block's span only went up to this inline. To work around I used the last inline's end to determine the span instead of the provided property, which fixed my issue.

Here's the code I used to work around it:

```csharp
var span = md is ParagraphBlock { Span: var pbSpan, Inline.LastChild.Span.End: var end } && pbSpan.End < end ? new SourceSpan(pbSpan.Start, end) : md.Span;
```

I suspect that this is a bug, and I would appreciate it if you could investigate further and possibly fix it. Thank you for your help!

**Comment by xoofx** [comment]
> I suspect that this is a bug, and I would appreciate it if you could investigate further and possibly fix it. Thank you for your help!

I have no time these days working on Markdig, so PR welcome.
