### ISSUE TITLE
YouTube Clip embeds not working

### ISSUE THREAD

**Issue by AlexMedia** [xoofx/markdig#703]
When using the media links extension, embedding YouTube clips from live streams does not seem to work.

Sample code:
```
![youtube](https://www.youtube.com/clip/UgkxDOpxfUB4DgnhIZV2CfDqkzXgLgBnSNYu)
```

For me, it gets rendered as a regular `<img>` tag with its `src` set to the URL provided, rather than generating an iframe with the embed.

**Comment by xoofx** [comment]
You need to replace `clip` by `embed`:

```md
![youtube](https://www.youtube.com/embed/UgkxDOpxfUB4DgnhIZV2CfDqkzXgLgBnSNYu)
```

I had to look at the code, the ["media link specs"](https://github.com/xoofx/markdig/blob/master/src/Markdig.Tests/Specs/MediaSpecs.md) don't mention this explicitly but the examples have `embed` or `watch`.
