### ISSUE TITLE
Error converting markdown with table in Html

### ISSUE THREAD

**Issue by CodingJarod** [xoofx/markdig#718]
Hi, 
I'm trying to convert a text with pipe table in it to html but I'm unable to match the expected result.
```
MarkdownDocument document = Markdown.Parse(stringWithMD, new MarkdownPipelineBuilder().UseAdvancedExtensions().Build());
result = document.ToHtml();
```
The document correctly identifies the table but when I execute the ToHtml it got converted in a series o <p> tag.

What am I missing?

Thanks

**Comment by MihaZupan** [comment]
You need to pass the pipeline to `ToHtml` as well. For performance reasons, you should also try to cache the pipeline object.
```c#
private static readonly MarkdownPipeline s_myPipeline = new MarkdownPipelineBuilder()
    .UseAdvancedExtensions()
    .Build();

MarkdownDocument document = Markdown.Parse(text, s_myPipeline);
string html = document.ToHtml(s_myPipeline); 
```

**Comment by CodingJarod** [comment]
Thank you!
