### ISSUE TITLE
In-fly shortcut reference links

### ISSUE THREAD

**Issue by hydroper** [xoofx/markdig#720]
I need to support `[q.b.f]` links for my language doc comments that refer to lexically-visible items.

I think that modifying [LinkInlineParser.ProcessLinkReference](https://github.com/xoofx/markdig/blob/b7cb169fd3a924e1e0d4e2e487a22c51caaedd10/src/Markdig/Parsers/Inlines/LinkInlineParser.cs#L119) should do it, passing some processor function to the pipeline that returns an URL string or null in case none was found. Could you add something like this to Markdig?

**Comment by xoofx** [comment]
You should probably instead use a post processing pass, like described [here](https://github.com/xoofx/markdig/issues/577#issuecomment-984737406) via `markdownObject.Descendants<LinkInline>()`. That won't require to modify Markdig and you can get this up and running with just a few lines of code.
