### ISSUE TITLE
Add support for converting from/to Telegram MarkdownV2

### ISSUE THREAD

**Issue by Laiteux** [xoofx/markdig#727]
(Idea)

https://core.telegram.org/bots/api#markdownv2-style

**Comment by xoofx** [comment]
I will decline. This is out of scope and can be developed outside of this repo (with maybe some markdig extensions) but it is also unclear if MarkdownV2 is actually a CommonMark compliant parser.

**Comment by MihaZupan** [comment]
This feels like something that could be exposed as part of https://github.com/TelegramBots/Telegram.Bot.
I'm pretty sure implementations of the "API representation => Markdown" conversion already exist. Feel free to ask in the telegram group of that project.
