### ISSUE TITLE
Can I process link targets before they're written?

### ISSUE THREAD

**Issue by deanebarker** [xoofx/markdig#732]
I would like to do some logical processing on the `HREF` value of a link. So, if the editor enters something like:

```
My name is [Deane](@deane).
```

I would like to capture the `@deane` value and do some processing on that value before it's written as the `HREF` attribute. I'd like to replace the value with another value.

Is there a mechanism for this? I couldn't find an event. Or do I need to replace the link parser/rendering completely?

**Comment by MihaZupan** [comment]
You can post-process the document and modify the URLs
```c#
MarkdownDocument document = Markdown.Parse(markdown, pipeline);

foreach (LinkInline link in document.Descendants<LinkInline>())
{
    if (link.Url.StartsWith('@'))
    {
        link.Url = $"https://github.com/{link.Url.AsSpan(1)}";
    }
}

string html = document.ToHtml(pipeline);
```

Or if you're creating `HtmlRenderer`s manually, you can set the `LinkRewriter` callback
```c#
renderer.LinkRewriter = url =>
    url.StartsWith('@') ? $"https://github.com/{url.AsSpan(1)}" : url;
```

**Comment by deanebarker** [comment]
Works beautifully, thank you.
