### ISSUE TITLE
4 backslashes are rendered as just 1

### ISSUE THREAD

**Issue by jansokoly** [xoofx/markdig#734]
Is there an explanation for why does `Markdown.ToHtml("\\\\contoso.com")` output `\contoso.com`? I would expect it to output 2 backslashes, i.e. `\\contoso.com`.

A workaround seems to be using 6 backslashes `Markdown.ToHtml("\\\\\\contoso.com")` to get 2 at output, but I'm trying to understand the logic here and can't find an answer.

Executable snippet: https://dotnetfiddle.net/XVxnyQ

With [commonmark.js dingus](https://spec.commonmark.org/dingus/), 4 backslashes result in 2 at output, as predicted:

![image](https://github.com/xoofx/markdig/assets/69093/3275c3a8-492e-4aa8-922d-234c3dfb413a)

Markdig 0.32.0.

Thank you.

**Comment by MihaZupan** [comment]
The C# string literal `"\\\\contoso.com"` means the text `\\contoso.com`.
Try `@"\\\\contoso.com"`
