### ISSUE TITLE
Can source line numbers appear in the rendered output?

### ISSUE THREAD

**Issue by deanebarker** [xoofx/markdig#745]
Is there any support or extension in MarkDig for corresponding output elements with the line number from the source? This would allow finding the correct line in the source from the output (i.e. -- synchronizing scrolling of source or output elements when doing side-by-side editing).

For example:

```
# Heading

This is some text.
```

Theoretical output:

```
<h1 data-line-number="1">Heading</h1>
<p data-line-number="3">This is some text.</p>
```

That's just an illustration -- I'm curious if there's anything in the library or extensions that does something similar to the example.

**Comment by xoofx** [comment]
There is the [`pipeline.UsePragmaLines()` extension](https://github.com/xoofx/markdig/blob/master/src/Markdig/Extensions/PragmaLines/PragmaLineExtension.cs)

This is what the Markdown Editor for Visual Studio is using for example [here](https://github.com/madskristensen/MarkdownEditor/blob/a4484fbbd92c3b691cb3d3408832462e2f6edde8/src/MarkdownEditor.Shared/Parsing/MarkdownFactory.cs#L24)

**Comment by deanebarker** [comment]
Perfect. I suspected that it existed, but I couldn't find it (TIL: what "pragma" means). Thank you.

**Comment by deanebarker** [comment]
For anyone following this, here's what `UsePragmaLines()` returns for the example above (clearly, it's 0-based):

```
<h1 id="pragma-line-0">Heading</h1>
<p id="pragma-line-2">This is some text.</p>
```
