### ISSUE TITLE
Question: Sanitize Markdown

### ISSUE THREAD

**Issue by molinch** [xoofx/markdig#762]
First of all thanks for the awesome lib!

Are you aware of a possibility to parse a string that contains Markdown and sanitize it to ensure only the allowed Markdown functionalities remain?
In our case we want to guarantee we want to guarantee we can only use bold/italic/lists/links.

**Comment by xoofx** [comment]
> Are you aware of a possibility to parse a string that contains Markdown and sanitize it to ensure only the allowed Markdown functionalities remain?
> In our case we want to guarantee we want to guarantee we can only use bold/italic/lists/links.

Yes, it is possible. Markdig provides the full Abstract Syntax Tree (AST) of a parsed Markdown document. You can process this AST to remove any nodes that are not relevant for your case.

**Comment by molinch** [comment]
Merci Alexandre. I'll go that way :)
