### ISSUE TITLE
Add support for GitHub Markdown Alerts

### ISSUE THREAD

**Issue by xoofx** [xoofx/markdig#774]
See https://github.com/orgs/community/discussions/16925

```md
> [!NOTE]  
> Highlights information that users should take into account, even when skimming.

> [!TIP]
> Optional information to help a user be more successful.

> [!IMPORTANT]  
> Crucial information necessary for users to succeed.

> [!WARNING]  
> Critical content demanding immediate user attention due to potential risks.

> [!CAUTION]
> Negative potential consequences of an action.
```

rendered as:

> [!NOTE]  
> Highlights information that users should take into account, even when skimming.

> [!TIP]
> Optional information to help a user be more successful.

> [!IMPORTANT]  
> Crucial information necessary for users to succeed.

> [!WARNING]  
> Critical content demanding immediate user attention due to potential risks.

> [!CAUTION]
> Negative potential consequences of an action.

**Comment by jorge-moreira** [comment]
Hi Alexandre,

The objective here is to support a new type of block (i.e. AlertBlock) with it's own parser and renderer?
For the parser I would say that there's no doubt on what to do, although for the renderer I've some doubts on how we would support this to be rendered in html.

I'll be glad to help on.

**Comment by xoofx** [comment]
Added a tentative PR #776 to implement this feature.

**Comment by xoofx** [comment]
> The objective here is to support a new type of block (i.e. AlertBlock) with it's own parser and renderer? For the parser I would say that there's no doubt on what to do, although for the renderer I've some doubts on how we would support this to be rendered in html.
> 
> I'll be glad to help on.

Forgot to respond, as I was reading your question yesterday, and I started to play with a parser to see how problematic it would be to implement it and saw that it was in the end relatively small, so decided to complete the implementation. So, my apologies if I took over and thanks for the proposal for helping, I appreciate. 🙂
