### ISSUE TITLE
Is there any way to get AutoIdentifiers list?

### ISSUE THREAD

**Issue by Nyazira** [xoofx/markdig#796]
If markdown is as follows:
```
# 1 你好，世界
## 1.1 你好，世界
# 1 Hello World
## 2 Hello World
```
then it generates the following code:
```
<h1 id="section">1 你好，世界</h1>
<h2 id="section-1">1.1 你好，世界</h2>
<h1 id="hello-world">1 Hello World</h1>
<h2 id="hello-world-1">2 Hello World</h2>
```
Since markdown's title contains both Chinese and English characters, I can't predict what kind of Identifier the title will generate.
Is there any way to get a list of identifiers?
So I can generate a directory from the list.

**Comment by MihaZupan** [comment]
Try
```c#
MarkdownDocument document = Markdown.Parse(content, pipeline);

foreach (HeadingBlock heading in document.Descendants<HeadingBlock>())
{
    Console.WriteLine(heading.GetAttributes().Id);
}

string html = document.ToHtml(pipeline);
```

**Comment by Nyazira** [comment]
> Try
> 
> ```cs
> MarkdownDocument document = Markdown.Parse(content, pipeline);
> 
> foreach (HeadingBlock heading in document.Descendants<HeadingBlock>())
> {
>     Console.WriteLine(heading.GetAttributes().Id);
> }
> 
> string html = document.ToHtml(pipeline);
> ```

Thank you,it works！
