### ISSUE TITLE
AutoLinks: URL that contain underscore at end are not parsed correctly

### ISSUE THREAD

**Issue by hey-red** [xoofx/markdig#798]
Markdig 0.37.0

Example link: `https://github.com/xoofx/markdig_`
Result:  `<p><a href="https://github.com/xoofx/markdig">https://github.com/xoofx/markdig</a>_</p>`

```C#
var pipeline = new MarkdownPipelineBuilder().UseAdvancedExtensions().Build();
var result = Markdown.ToHtml("https://github.com/xoofx/markdig_", pipeline);

Console.WriteLine(result); //-> <p><a href="https://github.com/xoofx/markdig">https://github.com/xoofx/markdig</a>_</p>
```

Github has same behaviour, so it's not a bug I guess?
https://github.com/xoofx/markdig_

**Comment by MihaZupan** [comment]
This is intentional - some trailing punctuation characters are trimmed from autolinks.
See https://github.github.com/gfm/#extended-autolink-path-validation

I'd suggest enclosing potentially problematic links in brackets manually `<https://github.com/xoofx/markdig_>`

**Comment by hey-red** [comment]
Okay. Thanks for response.
