### ISSUE TITLE
angle brackets in footnote are not escaped

### ISSUE THREAD

**Issue by hddreier** [xoofx/markdig#803]
angle brackets in footnote should be converted to &lt; &gt; but aren't. Footnote:

`[^LoopEntity]: außer bei der klassischen imperativen For-Schleife mit Schleifenzähler oder Iterator (in C: for(<Initialisierung>;<Bedingung>;<Inkrement>), die letztlich nur syntaktischer Zucker für eine explizite Konstruktion mit GOTOs ist und ein Label einspart.`

HTML produced:
`<p id="5502">außer bei der klassischen imperativen For-Schleife mit Schleifenzähler oder Iterator (in C: for(<Initialisierung>;<Bedingung>;<Inkrement>), die letztlich nur syntaktischer Zucker für eine explizite Konstruktion mit GOTOs ist und ein Label einspart.<a href="#fnref:25" class="footnote-back-ref">&#8617;</a></p>`

Markdig 0.37

**Comment by xoofx** [comment]
Don't think it has anything to do with footnotes. I believe that <> are interpreted as HTML inlines as per the CommonMark spec [here](https://spec.commonmark.org/0.31.2/#raw-html).
