### ISSUE TITLE
Why is the hyperlink & automatically encoded as &amp;

### ISSUE THREAD

**Issue by colindcli** [xoofx/markdig#805]
```
var pipeline = new MarkdownPipelineBuilder().Build();
var md = @"[link](https://pan.test.com/s/?pwd=93d3&path=%2Fv%2Ffid)";
var doc = Markdown.Parse(md, pipeline);
var html = doc.ToHtml(pipeline);  //<p><a href="https://pan.test.com/s/?pwd=93d3&amp;path=%2Fv%2Ffid">link</a></p>
```

Output hyperlinks & automatically encode as &amp;

**Comment by xoofx** [comment]
I don't remember that it was clearly specified in the specs (left to the implementation), and babelmark indicates that most CommonMark implementation are escaping [here](https://babelmark.github.io/?text=%5Blink%5D(https%3A%2F%2Fpan.test.com%2Fs%2F%3Fpwd%3D93d3%26path%3D%252Fv%252Ffid))

It has been the behavior for more than 6 years now, so I don't think it is a problem.

**Comment by colindcli** [comment]
Indeed, this problem is not a big one. It would be better if you can keep the link as it is, or make a configuration. Thank you!
