### ISSUE TITLE
Hyperlinks not working?

### ISSUE THREAD

**Issue by stigzler** [xoofx/markdig#806]
Firstly, fab lib! Secondly, I'm missing something really obvious. All rendering fine, but when I click a hyperlink, nothing happens. My MD xaml:

```xaml
<md:MarkdownViewer Markdown="{Binding SelectedIssueViewModel.Body}" Style="{StaticResource MarkdownViewer}"/>
```
Style just an adaptation (just color changes) of the standard one provided by markdig. 

I also tried adding:

```xaml
Hyperlink.RequestNavigate="MarkdownViewer_RequestNavigate"
``` 

but the event never fires. 

SelectedIssueViewModel.Body is just a text property. 

What am I missing?

**Comment by xoofx** [comment]
Markdig does not provide any direct support for XAML, so this has to be reported to the correct repository.

**Comment by stigzler** [comment]
Thanks for the reply - where would I find the correct repository?

**Comment by xoofx** [comment]
> where would I find the correct repository?

I don't know, you have added likely a NuGet package to your project to have that support, so I would start from there. There is no `MarkdownViewer` class in this repository.

**Comment by stigzler** [comment]
My apologies. It was markdig.wpf ([here](https://github.com/Kryptos-FR/markdig.wpf)). Will post over there.
