### ISSUE TITLE
"Value cannot be null" Error When Installing "markdig" from Nuget

### ISSUE THREAD

**Issue by nepgituser** [xoofx/markdig#810]
Hello. I tried to install Markdig from the Nuget package and am getting the following NULL error (see below, copied from terminal). Have tried it on two different computers and both act the same. Also, I renamed the Nuget cache folder (%appdata%\Nuget) on one of them to refresh it, but that didn't make a difference either. Lastly, I tried installing the next latest version (0.36.2) and it didn't work. Guess that means it's related to my two computers. What am I doing wrong? Thanks.

```
*PS C:\Users\me\source\repos\Markdig\Markdig> dotnet add "c:\Users\me\source\repos\Markdig\Markdig\Markdig.csproj" package "Markdig" -v "0.37.0"
  Determining projects to restore...
  Writing C:\Users\me\AppData\Local\Temp\tmpts3rid.tmp
info : X.509 certificate chain validation will use the default trust store selected by .NET for code signing.
info : X.509 certificate chain validation will use the default trust store selected by .NET for timestamping.
info : Adding PackageReference for package 'Markdig' into project 'c:\Users\me\source\repos\Markdig\Markdig\Markdig.csproj'.    
info : Restoring packages for c:\Users\me\source\repos\Markdig\Markdig\Markdig.csproj...
error: NU1108: Cycle detected. 
error:   Markdig -> Markdig (>= 0.37.0).
info : Package 'Markdig' is compatible with all the specified frameworks in project 'c:\Users\me\source\repos\Markdig\Markdig\Markdig.csproj'.
error: Value cannot be null. (Parameter 'path1')*
```

**Comment by xoofx** [comment]
Definitely an install/setup problem.

Not sure adding a `Markdig` PackageReference to a `Markdig.csproj` is a good idea to start with. The dll of your project will override the one from Markdig. Use different folder names. Nothing will correct correctly.

**Comment by nepgituser** [comment]
Changing the folder/project name fixed it. I was just doing some testing, not an actual project yet, so I didn't come up with a better name. Live and learn I guess. At any rate, it is working now. Thank you for the quick response.
