### ISSUE TITLE
Left margin with <ol><li>

### ISSUE THREAD

**Issue by tossnet** [xoofx/markdig#833]
I'm having a problem aligning the lists. My screenshot will explain it better: 

![image](https://github.com/user-attachments/assets/11bf6550-2514-4763-a2c7-f496c2208d1e)
Does anyone have a tip for solving this problem?

**Comment by tossnet** [comment]
yep : 
`Le 17 décembre, Kevin a les activités suivantes :\n\n1. **Animation** - Toute la journée.\n2. **Cours** - De 10h00 à 12h00.\n\nSi tu as besoin de plus d'informations, n'hésite pas à demander!`

and the result `Markdown.ToHtml(response)` :
```
<div class="bot-message" b-85l8jvojjl=""><!--!--><p>Le 17 décembre, Kevin a les activités suivantes :</p>
<ol>
<li><strong>Animation</strong> - Toute la journée.</li>
<li><strong>Cours</strong> - De 10h00 à 12h00.</li>
</ol>
<p>Si tu as besoin de plus d'informations, n'hésite pas à demander!</p>
</div>
```

**Comment by xoofx** [comment]
Ok thanks, [here](https://babelmark.github.io/?text=Le+17+d%C3%A9cembre%2C+Kevin+a+les+activit%C3%A9s+suivantes+%3A%0A%0A1.+**Animation**+-+Toute+la+journ%C3%A9e.%0A2.+**Cours**+-+De+10h00+%C3%A0+12h00.%0A%0ASi+tu+as+besoin+de+plus+d%27informations%2C+n%27h%C3%A9site+pas+%C3%A0+demander!) is the babelmark repro.

I don't see a problem here, so not sure what is it exactly. The generated HTML is correct. But if it is a visual alignment problem, it is mostly likely your CSS, not markdig.

**Comment by tossnet** [comment]
I'm sorry, that's what I just thought... I'll dig out those css and use :unset;
